import assert from 'node:assert/strict';
import { buildRhTvBody, defaultRhTvApi, RHTV_ORIGIN } from '../src/rhtvBridge';
import { buildVideoApiBody, parseVideoApiResult, videoApiSubmitEndpoint } from '../src/videoGenerationApi';
import { videoTaskExecutionScope, videoTaskOccupiesGenerationSlot } from '../src/videoGenerationQueue';
import { videoH3PictureNumbers } from '../src/videoH3ReferenceBinding';
import { availableVideoParameterKeys } from '../src/videoOutputParameters';
import type { VideoGenerationDraft } from '../src/videoGenerationTypes';
import type { VideoGenerationTask } from '../src/types';
const draft: VideoGenerationDraft = { backend: 'api', name: 'test', prompt: '<Picture 4> <d>原对白</d>', parameters: {},
  references: [{ assetId: 'a', slotIndex: 0, role: 'character', characterIds: ['one','two'] }, { assetId: 'b', slotIndex: 3, role: 'scene', characterIds: [] }] };
const body = buildRhTvBody(defaultRhTvApi, draft, ['a','b']);
assert.equal(body.prompt, draft.prompt);
assert.deepEqual(body.references.map((ref) => ref.slot_index), [0,3]);
assert.deepEqual(body.references.map((ref) => ref.character_ids), [['one','two'],[]]);
assert.equal(body.parameters.duration, 5);
assert.equal(body.cost_policy, 'free_only');
assert.throws(() => buildRhTvBody({ ...defaultRhTvApi, rhtvMode: 'first_last' }, draft, ['a','b']), /首尾帧/);
assert.throws(() => buildRhTvBody({ ...defaultRhTvApi, rhtvMode: 'text' }, draft, ['a','b']), /文生视频/);
assert.throws(() => buildRhTvBody(defaultRhTvApi, { ...draft, parameters: { seed: 3 } }, ['a','b']), /未静默忽略/);
assert.throws(() => buildRhTvBody(defaultRhTvApi, draft, ['a']), /不完整/);
assert.deepEqual(buildVideoApiBody(defaultRhTvApi, draft, ['a','b']), body);
assert.equal(videoApiSubmitEndpoint({ ...defaultRhTvApi, endpoint: 'https://attacker.example' }), `${RHTV_ORIGIN}/v1/videos`);
assert.deepEqual(videoH3PictureNumbers(draft.references, { backend: 'api', api: defaultRhTvApi }).numbers, [1,2]);
assert.equal(videoH3PictureNumbers(draft.references, { backend: 'api', api: { ...defaultRhTvApi, rhtvMode: 'first_last' } }).numbers, undefined);
const task: VideoGenerationTask = { id: 'task', storyboardId: '', targetId: 'rhTV', status: 'submitted', requestBody: {}, createdAt: 1, updatedAt: 1,
  videoJob: { stage: 'queued', snapshot: { projectId: 'project', clientId: 'client', images: [], draft, connection: { backend: 'api', api: defaultRhTvApi } }, preparation: { version: 1, phase: 'acknowledged', uploadedImages: [] } }, remoteTaskId: 'local-id' };
assert.equal(videoTaskExecutionScope(task).key, 'api:rhtv-local-single-account');
assert.equal(videoTaskOccupiesGenerationSlot(task), true);
assert.equal(videoTaskOccupiesGenerationSlot({ ...task, response: { id: 'local-id', status: 'failed', terminal_confirmed: true } }), false);
assert.equal(videoTaskOccupiesGenerationSlot({ ...task, response: { id: 'local-id', status: 'failed' } }), true);
assert.deepEqual(availableVideoParameterKeys('api', defaultRhTvApi), ['duration','resolution']);
assert.deepEqual(availableVideoParameterKeys('comfyui', defaultRhTvApi, { mapping: { images: [], prompt: [], parameters: { width: { nodeId: '1', inputName: 'width' } } } }), ['width']);
const waiting = parseVideoApiResult({ id: 'one', status: 'waiting_review', message: '等待核对' }, defaultRhTvApi);
assert.equal(waiting.status, 'submitted'); assert.equal(waiting.message, '等待核对');
assert.equal(parseVideoApiResult({ id: 'one', status: 'submission_unknown' }, defaultRhTvApi).stage, 'submission-unknown');
assert.equal(parseVideoApiResult({ id: 'one', status: 'running' }, defaultRhTvApi).status, 'running');
assert.equal(parseVideoApiResult({ id: 'one', status: 'download_failed' }, defaultRhTvApi).status, 'running');
assert.equal(parseVideoApiResult({ id: 'one', status: 'paused' }, defaultRhTvApi).status, 'submitted');
assert.equal(parseVideoApiResult({ id: 'one', status: 'succeeded', result_url: 'https://wrong.example/video.mp4' }, defaultRhTvApi).resultUrl, undefined);
assert.equal(parseVideoApiResult({ id: 'one', status: 'succeeded', result_url: `${RHTV_ORIGIN}/v1/videos/one/content` }, defaultRhTvApi).status, 'succeeded');
console.log('rhTV protocol: bindings, modes, status and stable scope passed');
