import type {
  Character,
  Location,
  Prop,
  ReferenceAsset,
  Storyboard,
  TargetOutput,
} from './types';
import {
  compileTargetPrompt,
  type CompiledTargetPrompt,
  type PromptAdapterInput,
  type PromptReferenceInput,
  type PromptSubjectDefinitionInput,
} from './promptAdapters';
import { resolveModelProfile } from './modelProfiles';
import { orderReferencedAssets, usesNsfwDetailMode } from './promptEngine';
import { sourceContentHash } from './sourceContentHash';
import {
  OFFICIAL_H3_SOURCE_VERSION,
  OFFICIAL_H3_PRIVATE_SCOPE_REVISION,
  canonicalPromptSource,
  needsOfficialPrivateScopeRevision,
  officialH3CanonicalSourceMatches,
} from './officialH3SourceIdentity';
export { officialH3CanonicalSourceMatches } from './officialH3SourceIdentity';
import { normalizeCanonicalTimelineSoundCueTimes } from './masterTimeline';
import { bindVerifiedGeneratedH3CharacterReferences, buildBudgetedOfficialH3References } from './officialReferenceBudget';
import { getH3PromptProtocolIssue } from './h3PromptProtocol';
import { publicVideoContinuityLock, selectedVideoPrivateFacts } from './videoPrivateScope';
import {
  hasExplicitClothingStateChange,
} from './continuity';
import {
  characterVariantDisplayName,
  characterVariantFormLabel,
  characterVariantPromptFacts,
} from './characterVariants';
import {
  canUseNsfwPrivateProfileAssetForStoryboardShot,
  characterNsfwProfileText,
  isNsfwPrivateProfileAsset,
  nsfwPrivateReferenceResponsibility,
} from './nsfwPrivateAssets';

export const OFFICIAL_H3_TARGET_ID = 'minimax-h3';

export interface OfficialH3ProjectContext {
  assets: readonly ReferenceAsset[];
  characters?: readonly Character[];
  locations?: readonly Location[];
  props?: readonly Prop[];
  sceneContent?: string;
}

const clean = (value: unknown): string => typeof value === 'string' ? value.trim() : '';

/** Accept the legacy h3/minimaxh3 aliases while keeping unknown targets out. */
export const isOfficialH3TargetId = (value: unknown): boolean => (
  typeof value === 'string'
  && resolveModelProfile(value).id === OFFICIAL_H3_TARGET_ID
);

const referencedAssetIds = (board: Storyboard): string[] => [
  ...board.shots.flatMap((shot) => shot.referenceAssetIds || []),
  ...(board.globalReferenceAssetIds || []),
  board.firstFrameAssetId || '',
  board.lastFrameAssetId || '',
  ...(board.audioLedger || []).map((cue) => cue.sourceAssetId || ''),
].filter(Boolean);

/**
 * A storyboard image generated by this board is a downstream visual output,
 * not a new source fact for the official video prompt.  The image batch binds
 * each result back to its shot (and, for boundary images, to first/last-frame
 * fields), so treating those ids as ordinary references would immediately
 * change the H3 source fingerprint while the batch is still completing.
 *
 * A user can intentionally promote any asset to a global reference.  In that
 * case the id is kept and the official prompt is expected to recompile around
 * the newly selected source image.
 */
const isAutomaticStoryboardOutput = (
  board: Storyboard,
  asset: ReferenceAsset,
): boolean => asset.source === 'generated'
  && asset.sourceStoryboardId === board.id
  && !(board.globalReferenceAssetIds || []).includes(asset.id);

type OfficialH3ReferenceCharacter = Pick<Character, 'id' | 'name' | 'apparentAge'>;

/** Resolve only the exact shots to which a private image is currently bound.
 * A project-wide/global id cannot establish an adult NSFW shot scope and is
 * therefore never sufficient on its own. Boundary references are tested only
 * against their corresponding first/last shot. A private image mentioned only
 * by unrelated metadata (for example an audio cue) has no visual target and
 * therefore fails closed. */
const privateReferenceTargetShots = (
  board: Storyboard,
  assetId: string,
): Storyboard['shots'] => {
  const targeted = new Map<string, Storyboard['shots'][number]>();
  board.shots.forEach((shot) => {
    if ((shot.referenceAssetIds || []).includes(assetId)) targeted.set(shot.id, shot);
  });
  if (board.firstFrameAssetId === assetId && board.shots[0]) {
    targeted.set(board.shots[0].id, board.shots[0]);
  }
  const lastShot = board.shots[board.shots.length - 1];
  if (board.lastFrameAssetId === assetId && lastShot) targeted.set(lastShot.id, lastShot);
  return [...targeted.values()];
};

const canUseOfficialH3PrivateReference = (
  board: Storyboard,
  asset: ReferenceAsset,
  characters: readonly OfficialH3ReferenceCharacter[],
): boolean => privateReferenceTargetShots(board, asset.id).some((shot) => (
  canUseNsfwPrivateProfileAssetForStoryboardShot(asset, board, shot, characters)
));

const officialSourceAssets = (
  board: Storyboard,
  assets: readonly ReferenceAsset[],
  characters: readonly OfficialH3ReferenceCharacter[] = [],
): ReferenceAsset[] => assets.filter((asset) => (
  !isAutomaticStoryboardOutput(board, asset)
  && (
    !isNsfwPrivateProfileAsset(asset)
    || canUseOfficialH3PrivateReference(board, asset, characters)
  )
));

export const collectOfficialH3ReferenceAssets = (
  board: Storyboard,
  assets: readonly ReferenceAsset[],
  characters: readonly OfficialH3ReferenceCharacter[] = [],
): ReferenceAsset[] => {
  // Keep this filtering at the collection boundary so compilation and source
  // fingerprinting consume exactly the same reference manifest.
  const sourceAssets = officialSourceAssets(board, assets, characters);
  const ordered = orderReferencedAssets(board.shots, [...sourceAssets]);
  const seen = new Set(ordered.map((asset) => asset.id));
  const byId = new Map(sourceAssets.map((asset) => [asset.id, asset]));
  for (const id of referencedAssetIds(board)) {
    if (seen.has(id)) continue;
    const asset = byId.get(id);
    if (!asset) continue;
    seen.add(id);
    ordered.push(asset);
  }
  return ordered;
};

export const buildOfficialH3References = (
  board: Storyboard,
  assets: readonly ReferenceAsset[],
  characters: readonly OfficialH3ReferenceCharacter[] = [],
): PromptReferenceInput[] => collectOfficialH3ReferenceAssets(board, assets, characters).map((asset) => ({
  ...asset,
  mediaType: asset.mediaType || 'image',
  referenceRole: asset.referenceRole
    || (asset.role === 'character'
      ? 'character'
      : asset.role === 'scene'
        ? 'scene'
        : asset.role === 'prop'
          ? 'prop'
          : asset.role),
  // A private image's generation prompt/anchor may describe nudity as a
  // timeless identity fact. Replace it with a shot-scoped responsibility so
  // the current dynamic clothing state always remains authoritative.
  responsibility: isNsfwPrivateProfileAsset(asset)
    ? nsfwPrivateReferenceResponsibility(asset)
    : asset.visualAnchor || asset.prompt || undefined,
}));

const isPrivatePromptReference = (reference: PromptReferenceInput): boolean => (
  isNsfwPrivateProfileAsset(reference as unknown as ReferenceAsset)
);

const referencedIdsForEntity = (
  entityId: string,
  entityAssetIds: readonly string[],
  references: readonly PromptReferenceInput[],
): string[] => {
  const availableById = new Map(references
    .map((reference) => [clean(reference.id), reference] as const)
    .filter(([id]) => Boolean(id)));
  const direct = entityAssetIds.filter((id) => {
    const reference = availableById.get(id);
    if (!reference) return false;
    // General composite pictures may intentionally be shared when they have no
    // owner. Once an asset carries a sourceEntityId, however, that explicit
    // binding is authoritative for every form: a stale entity card must not
    // make an original-form image leak into a transformed sibling. Private
    // images keep the same rule and are never shareable across entities.
    const sourceEntityId = clean(reference.sourceEntityId);
    return !sourceEntityId || sourceEntityId === entityId;
  });
  const sourced = references
    .filter((reference) => clean(reference.sourceEntityId) === entityId)
    .map((reference) => clean(reference.id))
    .filter(Boolean);
  return [...new Set([...direct, ...sourced])];
};

const officialH3EntityEvidence = (board: Storyboard): string => [
  board.promptPlan?.canonicalPrompt || board.finalPrompt,
  ...board.shots.flatMap((shot) => [
    shot.subject,
    shot.action,
    shot.camera,
    shot.result,
    shot.prompt,
    shot.nsfwContinuity?.nudity,
    shot.nsfwContinuity?.clothingState,
    Number.isInteger(shot.sourceStart)
      && Number.isInteger(shot.sourceEnd)
      && (shot.sourceStart as number) >= 0
      && (shot.sourceEnd as number) > (shot.sourceStart as number)
      ? (board.sourceStoryContent || '').slice(shot.sourceStart, shot.sourceEnd)
      : '',
  ]),
].map(clean).filter(Boolean).join('\n');

const officialH3HasDynamicClothing = (board: Storyboard): boolean => (
  hasExplicitClothingStateChange(officialH3EntityEvidence(board))
);

/**
 * Character cards and the canonical timeline have different scopes. A fixed
 * wardrobe belongs to the card; once this board contains nudity, removal, or
 * redressing, that wardrobe must not be repeated as a video-wide constraint.
 * The canonical Shot state remains authoritative and explicitly carries the
 * worn/off-body result at every cut.
 */
const officialH3Constraints = (
  board: Storyboard,
  dynamicClothing: boolean,
): string[] => {
  const constraints = (board.promptPlan?.constraints || [
    publicVideoContinuityLock(board.globalLock),
    board.extraRequirement ? `制作要求：${board.extraRequirement}` : '',
  ].filter(Boolean)).map((constraint) => /^制作要求\s*[：:]/u.test(constraint.trim())
    ? constraint
    : publicVideoContinuityLock(constraint)).filter(Boolean);
  if (!dynamicClothing) return [...constraints];
  return constraints.flatMap((constraint) => clean(constraint).split(/\r?\n/u))
    .map(clean)
    .filter((constraint) => {
      // A compact PromptPlan constraint may contain the complete automatic
      // character lock on one line. Drop that automatic identity duplicate;
      // subjectDefinitions already preserve stable identity and appearance.
      if (/^(?:连续性锚点\s*[：:]\s*)?固定人物\s*[：:]/u.test(constraint)) return false;
      if (/^同一镜头组中的人物身份、默认衣橱\/身份服装基底/u.test(constraint)) return false;
      return true;
    });
};

const fallbackCompositeReferenceIds = (
  name: string,
  evidence: string,
  references: readonly PromptReferenceInput[],
): string[] => {
  if (!name || !evidence.includes(name)) return [];
  const visualReferences = references.filter((reference) => (
    clean(reference.mediaType).toLowerCase() !== 'audio'
    && !isPrivatePromptReference(reference)
  ));
  if (visualReferences.length !== 1) return [];
  const id = clean(visualReferences[0].id);
  return id ? [id] : [];
};

const description = (...parts: unknown[]): string => parts.map(clean).filter(Boolean).join('；');

export const buildOfficialH3SubjectDefinitions = (
  board: Storyboard,
  context: OfficialH3ProjectContext,
  references = buildOfficialH3References(board, context.assets, context.characters),
): PromptSubjectDefinitionInput[] => {
  const definitions: PromptSubjectDefinitionInput[] = [];
  const entityEvidence = officialH3EntityEvidence(board);
  const dynamicClothing = officialH3HasDynamicClothing(board);
  const characters = (context.characters || []).filter((character) => !character.dossier?.archivedIntoCharacterId);
  for (const character of characters) {
    const displayName = characterVariantDisplayName(character) || character.name;
    const characterBase = String((character as Character & { baseName?: string; variantOf?: string }).baseName
      || (character as Character & { variantOf?: string }).variantOf
      || character.name).trim();
    const hasSpecificSiblingEvidence = characters.some((sibling) => (
      sibling.id !== character.id
      && String((sibling as Character & { baseName?: string; variantOf?: string }).baseName
        || (sibling as Character & { variantOf?: string }).variantOf
        || sibling.name).trim() === characterBase
      && characterVariantFormLabel(sibling)
      && entityEvidence.includes(characterVariantDisplayName(sibling))
    ));
    // “泰罗” is a substring of “泰罗·女性形态”. Once a concrete form is
    // present in this board, suppress the legacy bare card instead of leaking
    // its reference/appearance into the transformed shot.
    if (hasSpecificSiblingEvidence && !characterVariantFormLabel(character)) continue;
    if (!entityEvidence.includes(displayName) && !entityEvidence.includes(character.name)) continue;
    const directIds = referencedIdsForEntity(character.id, character.assetIds, references);
    const visualReferences = references.filter((reference) => (
      clean(reference.mediaType).toLowerCase() !== 'audio'
      && !isPrivatePromptReference(reference)
    ));
    // A variant without its own image must never inherit the only image of a
    // sibling form (for example the original male card after a female
    // transformation). Unowned/composite references keep the legacy fallback.
    const hasOwnedSiblingOnly = visualReferences.some((reference) => (
      clean(reference.sourceEntityId)
      && clean(reference.sourceEntityId) !== character.id
    )) && !visualReferences.some((reference) => clean(reference.sourceEntityId) === character.id);
    const referenceAssetIds = directIds.length
      ? directIds
      : hasOwnedSiblingOnly
        ? []
        : fallbackCompositeReferenceIds(displayName, entityEvidence, references);
    definitions.push({
      name: displayName,
      ...(('baseName' in character) ? { baseName: String((character as Character & { baseName?: string }).baseName || '') } : {}),
      ...(('formLabel' in character) ? { formLabel: String((character as Character & { formLabel?: string }).formLabel || '') } : {}),
      ...(('variantOf' in character) ? { variantOf: String((character as Character & { variantOf?: string }).variantOf || '') } : {}),
      ...(('transformationType' in character) ? { transformationType: String((character as Character & { transformationType?: string }).transformationType || '') } : {}),
      kind: 'character',
      gender: character.gender,
      race: character.race,
      morphology: character.morphology,
      bodyPlan: character.bodyPlan,
      appearance: description(
        ...characterVariantPromptFacts(character),
        character.apparentAge,
        character.appearance,
      ),
      outfit: dynamicClothing ? undefined : character.outfit,
      // Keep the inventory available to the AI so removing one garment does
      // not erase all remaining clothes. It is not a global wearing state.
      wardrobeBaseline: dynamicClothing ? character.outfit : undefined,
      // Existing character anchors often repeat the default costume. During a
      // clothing transition, appearance plus stable body facts carry identity;
      // keep only the separately modelled signature props here.
      anchor: description(dynamicClothing ? '' : character.anchor, character.signatureProps),
      motion: character.motionHabits,
      referenceAssetIds,
    });
  }
  for (const location of context.locations || []) {
    if (!entityEvidence.includes(location.name)) continue;
    const directIds = referencedIdsForEntity(location.id, location.assetIds, references);
    const referenceAssetIds = directIds.length
      ? directIds
      : fallbackCompositeReferenceIds(location.name, entityEvidence, references);
    definitions.push({
      name: location.name,
      kind: 'scene',
      description: description(
        location.description,
        location.timeWeather,
        location.lighting,
        location.palette,
        location.fixedProps,
      ),
      anchor: location.anchor,
      referenceAssetIds,
    });
  }
  for (const prop of context.props || []) {
    if (!entityEvidence.includes(prop.name)) continue;
    const directIds = referencedIdsForEntity(prop.id, prop.assetIds, references);
    const referenceAssetIds = directIds.length
      ? directIds
      : fallbackCompositeReferenceIds(prop.name, entityEvidence, references);
    definitions.push({
      name: prop.name,
      kind: 'prop',
      description: description(prop.category, prop.material, prop.appearance, prop.effect, prop.stateRules),
      referenceAssetIds,
    });
  }
  return bindVerifiedGeneratedH3CharacterReferences(definitions, references);
};

export const buildOfficialH3CompileInput = (
  board: Storyboard,
  context: OfficialH3ProjectContext,
): PromptAdapterInput => {
  const sourceReferences = buildOfficialH3References(board, context.assets, context.characters);
  const subjectDefinitions = buildOfficialH3SubjectDefinitions(board, context, sourceReferences);
  const references = buildBudgetedOfficialH3References(sourceReferences, subjectDefinitions);
  const dynamicClothing = officialH3HasDynamicClothing(board);
  const sourceText = [
    board.sourceStoryContent,
    ...(board.sourceSceneSnapshots || []).map((snapshot) => snapshot.content),
    context.sceneContent,
  ].filter(Boolean).join('\n');
  const soundTimelineOffset = board.sequencePlanId && board.segmentId
    && typeof board.globalStartSec === 'number' && Number.isFinite(board.globalStartSec)
    && board.globalStartSec >= 0
    ? board.globalStartSec
    : 0;
  return {
    canonicalPrompt: normalizeCanonicalTimelineSoundCueTimes(canonicalPromptSource(board), soundTimelineOffset),
    durationSec: board.promptPlan?.durationSec || board.durationSec,
    aspectRatio: board.promptPlan?.aspectRatio || board.aspectRatio,
    resolution: board.promptPlan?.resolution || board.resolution,
    audioMode: board.promptPlan?.audioMode || board.audioMode,
    references,
    subjectDefinitions,
    shotPrivateDetails: board.shots.flatMap((shot, index) => selectedVideoPrivateFacts(
      context.characters || [], shot.visiblePrivatePartsByCharacter,
    ).map((fact) => ({
      shotIndex: index + 1,
      subjectName: fact.name,
      description: characterNsfwProfileText(fact.profile, fact.parts),
    }))),
    targetId: OFFICIAL_H3_TARGET_ID,
    detailMode: 'concise',
    nsfwDetail: usesNsfwDetailMode(sourceText, board.extraRequirement || '') || undefined,
    constraints: officialH3Constraints(board, dynamicClothing),
  };
};

const officialH3FingerprintPayload = (input: PromptAdapterInput): string => JSON.stringify({
  canonicalPrompt: input.canonicalPrompt,
  durationSec: input.durationSec,
  aspectRatio: input.aspectRatio,
  resolution: input.resolution,
  audioMode: input.audioMode,
  references: (input.references || []).map((reference) => ({
    id: reference.id,
    name: reference.name,
    mediaType: reference.mediaType,
    type: reference.type,
    role: reference.role,
    referenceRole: reference.referenceRole,
    source: reference.source,
    sourceUrl: reference.sourceUrl,
    fileName: reference.fileName,
    // The binary reference may change while keeping its id/name and all
    // display metadata stable.  Carry the content checksum into the source
    // fingerprint so an official prompt cannot silently reuse a stale image.
    checksum: (reference as { checksum?: string }).checksum,
    url: reference.url,
    durationSec: reference.durationSec,
    duration: reference.duration,
    width: reference.width,
    height: reference.height,
    aspectRatio: reference.aspectRatio,
    firstFrame: reference.firstFrame,
    lastFrame: reference.lastFrame,
    // Storage normalizes absent bindings to []. They mean the same thing;
    // reloading an unchanged uploaded reference must not stale the Chinese
    // prompt and send an English-only retry back through conversion.
    targetBindings: reference.targetBindings || [],
    responsibility: reference.responsibility,
    description: reference.description,
    visualAnchor: reference.visualAnchor,
    sourceEntityId: reference.sourceEntityId,
    referenceScope: reference.referenceScope,
    nsfwPrivatePart: reference.nsfwPrivatePart,
    imageVariant: reference.imageVariant,
  })),
  subjectDefinitions: input.subjectDefinitions || [],
  ...(input.shotPrivateDetails?.length ? { shotPrivateDetails: input.shotPrivateDetails } : {}),
  constraints: input.constraints || [],
  nsfwDetail: input.nsfwDetail || false,
});

export const buildOfficialH3SourceFingerprint = (
  board: Storyboard,
  context: OfficialH3ProjectContext,
): string => {
  const compileInput = buildOfficialH3CompileInput(board, context);
  const canonicalHash = sourceContentHash(canonicalPromptSource(board));
  const completeHash = sourceContentHash(officialH3FingerprintPayload(compileInput));
  const scopeRevision = needsOfficialPrivateScopeRevision(board) ? OFFICIAL_H3_PRIVATE_SCOPE_REVISION : '';
  return `${OFFICIAL_H3_SOURCE_VERSION}:${canonicalHash}:${completeHash}${scopeRevision}`;
};

/** Keep workflow controls during either official-only refresh entry point. */
export const mergeOfficialH3Parameters = (
  board: Pick<Storyboard, 'targetModelId' | 'targetOutput'>,
  compiledParameters: Readonly<Record<string, unknown>>,
): Record<string, unknown> => {
  // Refreshing an H3 prompt must not reset a user's seed, sampler or other
  // workflow-specific controls. Only carry parameters from the same target;
  // compiler-owned fields below always follow the current storyboard input.
  const previousParameters = isOfficialH3TargetId(compiledParameters.model)
    && isOfficialH3TargetId(board.targetOutput?.targetId)
    && (!clean(board.targetModelId) || isOfficialH3TargetId(board.targetModelId))
    ? board.targetOutput?.parameters
    : undefined;
  return { ...previousParameters, ...compiledParameters };
};

export const compileOfficialH3Prompt = (
  board: Storyboard,
  context: OfficialH3ProjectContext,
): { compiled: CompiledTargetPrompt; output: TargetOutput; sourceFingerprint: string } => {
  const compiled = compileTargetPrompt(buildOfficialH3CompileInput(board, context));
  const output: TargetOutput = {
    targetId: compiled.targetId,
    prompt: compiled.prompt,
    parameters: mergeOfficialH3Parameters(board, compiled.parameters),
    referenceManifest: compiled.referenceManifest.assets.map((item) => ({ ...item })),
    warnings: [...compiled.warnings],
    generatedAt: Date.now(),
  };
  return {
    compiled,
    output,
    sourceFingerprint: buildOfficialH3SourceFingerprint(board, context),
  };
};

export const hasCurrentOfficialH3Prompt = (
  board: Storyboard,
  context?: OfficialH3ProjectContext,
): boolean => Boolean(
  !board.characterDossierDirty
  && isOfficialH3TargetId(board.targetModelId)
  && isOfficialH3TargetId(board.targetOutput?.targetId)
  && board.officialPromptZh?.trim()
  && !getH3PromptProtocolIssue(board.officialPromptZh)
  && board.targetOutput?.prompt === board.officialPromptZh
  && officialH3CanonicalSourceMatches(board)
  && (!context || board.officialPromptSource === buildOfficialH3SourceFingerprint(board, context)),
);

/** English is an independent derivative. Its absence must not invalidate a
 * qualified Chinese delivery or block Chinese submission/export. Freshness is
 * based on source identity, not a local interpretation of dialogue wording. */
export const hasCurrentOfficialH3EnglishPrompt = (
  board: Storyboard,
  context?: OfficialH3ProjectContext,
): boolean => Boolean(
  hasCurrentOfficialH3Prompt(board, context)
  && board.officialPromptEn?.trim()
  && !getH3PromptProtocolIssue(board.officialPromptEn, board.officialPromptZh)
  && board.officialPromptEnSource === board.officialPromptZh,
);

/**
 * Validate the exact H3 payload that is about to cross the HTTP boundary.
 *
 * This guard is intentionally independent from the renderer's selected board:
 * failed-task retries and manually edited request JSON must still point at a
 * current official artifact. Character length never blocks local submission.
 * The selected language chooses the matching saved Chinese/English delivery;
 * callers that do not track language retain the historical Chinese default.
 */
export const getOfficialH3SubmissionIssue = (
  body: Record<string, unknown>,
  board?: Storyboard,
  context?: OfficialH3ProjectContext,
  language: 'zh' | 'en' = 'zh',
): string | undefined => {
  if (!isOfficialH3TargetId(body.model)) return undefined;
  if (board?.characterDossierDirty) return '人物资料已更新，提示词待刷新；请先按新资料更新提示词后再提交。';
  const prompt = typeof body.prompt === 'string' ? body.prompt : '';
  if (!prompt.trim()) {
    return '当前 MiniMax H3 请求缺少有效提示词，请回到导演台重新生成官方交付稿。';
  }
  const current = language === 'en'
    ? board && context && hasCurrentOfficialH3EnglishPrompt(board, context)
    : board && context && hasCurrentOfficialH3Prompt(board, context);
  if (!current) {
    return '当前官方 MiniMax H3 交付稿已失效或尚未生成，请回到导演台重新生成后再提交。';
  }
  const officialPrompt = language === 'en' ? board?.officialPromptEn : board?.officialPromptZh;
  // The saved delivery is the model-authored artifact.  Do not normalize
  // whitespace here: even a seemingly harmless prefix/suffix change means
  // the bytes crossing the provider boundary are no longer that artifact.
  if (prompt !== (officialPrompt || '')) {
    return '请求中的提示词不是当前官方 H3 交付稿，请刷新请求体后再提交。';
  }
  return undefined;
};

export const applyOfficialH3Prompt = (
  board: Storyboard,
  context: OfficialH3ProjectContext,
): Storyboard => {
  const { output, sourceFingerprint } = compileOfficialH3Prompt(board, context);
  const chineseChanged = board.officialPromptZh !== output.prompt;
  return {
    ...board,
    targetModelId: OFFICIAL_H3_TARGET_ID,
    targetOutput: output,
    officialPromptZh: output.prompt,
    officialPromptSource: sourceFingerprint,
    officialPromptEn: chineseChanged ? '' : board.officialPromptEn,
    officialPromptEnSource: chineseChanged ? '' : board.officialPromptEnSource,
    officialPromptEnError: chineseChanged ? '' : board.officialPromptEnError,
  };
};

/**
 * Preserve the saved delivery after image generation enriches character facts.
 * A finished H3 body may contain AI staging repairs that are absent from the
 * canonical timeline; local recompilation would silently overwrite them.
 * Keep the original fingerprint and English too. If facts really changed,
 * normal freshness checks mark this artifact stale until an explicit AI
 * regeneration. No-op updates remain current without rewriting anything.
 */
export const refreshOfficialH3PromptAfterSourceUpdate = (
  board: Storyboard,
  _previousContext: OfficialH3ProjectContext,
  _nextContext: OfficialH3ProjectContext,
): Storyboard => board;
